ingress:
  rules:
    - component:
        name: web
      match:
        path:
          prefix: /
name: claude-to-chatgpt-php-digital-ocean
services:
  - name: web
    github:
      repo: samestrin/claude-to-chatgpt-php-digital-ocean
      repo_clone_url: https://github.com/samestrin/claude-to-chatgpt-php-digital-ocean.git
      branch: main
    environment_slug: php
    build_command: composer install
    run_command: php -S 0.0.0.0:8080 -t .
    http_port: 8080
    source_dir: /
    routes:
      - path: /
