ingress:
  rules:
    - component:
        name: web
      match:
        path:
          prefix: /
name: claude-to-chatgpt-php-digital-ocean
services:
  - name: web
    github:
      repo: samestrin/claude-to-chatgpt-php-digital-ocean
      branch: main
    environment_slug: php
    build_command: composer install
    run_command: heroku-php-nginx -C nginx.conf .
    http_port: 8080
    source_dir: /
